export const AGREGAR_CATEGORIA = "AGREGAR_CATEGORIA";
export const DESCARGA_CATEGORIA = "DESCARGA_CATEGORIA";
export const DESCARGA_CATEGORIA_EXITO = "DESCARGA_CATEGORIA_EXITO";
export const DESCARGA_CATEGORIA_ERROR = "DESCARGA_CATEGORIA_ERROR";
